ZcashFoundation/zcash-grant-system

frontend/client/components/CreateFlow/Review.tsx

Closes #65. Fixes the invite count including accepted and rejected invites. To test, invite two people, accept with one, and go to review to confirm the count is correct.

Fix incorrect pending invites count

---

frontend/client/components/Header/Auth.less
frontend/client/components/Header/Auth.tsx

Closes #59. Fixes the flash of "Sign in" by using the correct prop, and changing the way the render function works to not insert a new node.
If you want to test this, you have to add an artificial sleep to /me in `backend/grant/user/views.py` because it takes longer for the CSS to load than for the endpoint to return (Which is why this issue wasn't caught in dev.)
```diff
from flask_yoloapi import endpoint, parameter
+from time import sleep
def get_me():
+    sleep(2)

Fade auth in, invisible while checking.

---

backend/grant/proposal/views.py
frontend/client/components/AuthRoute.tsx
frontend/client/components/ContributionModal/index.tsx
frontend/client/components/CreateFlow/Final.tsx
frontend/client/components/LinkableTabs.tsx
frontend/client/components/Profile/index.tsx
frontend/client/components/Proposal/index.tsx
frontend/client/components/Settings/index.tsx
frontend/client/styles/html.less

Closes #64.
Creates a new component called `<LinkableTabs>` that wraps Ant's `<Tabs>` component. It checks the query string for `?tab=[tab]` and sets that tab to the default. If you pass `scrollToTab`, it'll also smooth-scroll down to the specified tab's location on screen. All existing `<Tabs>` have been replaced with `<LinkableTabs>`, and all links to specific tabs have been updated.
This also implements a lot of query param forwarding to redirects, and improves the initial auth redirect. For future reference, the easy way to do this is:
```diff
- return <Redirect to="/path" />;
+ const { location } = this.props;
+ return <Redirect to={{ ...redirect, pathname: '/path' }} />;
```
1. While logged in, go to `/profile?tab=invitations`, confirm the query param was carried to …

Link to specific tabs from query param

---

admin/src/components/Emails/emails.ts
backend/grant/admin/example_emails.py
backend/grant/admin/views.py
backend/grant/comment/models.py
backend/grant/email/send.py
backend/grant/proposal/models.py
backend/grant/proposal/views.py
backend/grant/templates/emails/comment_reply.html
backend/grant/templates/emails/comment_reply.txt
backend/grant/templates/emails/contribution_update.html
backend/grant/templates/emails/contribution_update.txt
backend/grant/templates/emails/proposal_comment.html
backend/grant/templates/emails/proposal_comment.txt
backend/grant/templates/emails/proposal_contribution.html
backend/grant/templates/emails/proposal_contribution.txt
backend/grant/utils/misc.py

Knocks out a bunch of #12, still not all. Relies on #75.
* Adds emails for the following cases:
* Proposal comments for proposal team
* Comment replies for comment creator
* Proposal updates for proposal contributors
* Contribution confirmation for contributor & proposal team
* Fixes the email admin from #75.
* Create two accounts, and on one of them a new proposal
* As another user, post a comment on that proposal. Confirm you get an email as the creator of the proposal.
* As the creator of the proposal, reply to that comment. Confirm you get an email as the author of the parent comment.
* As the non-creator, fund the proposal. Confirm you get a confirmation email after it confirms. Confirm you get an email as the proposal creator that you got a new contribution.
* As the creator of the …

A bunch of emails

---

admin/README.md
admin/src/components/Emails/Example.tsx
admin/src/components/Template/index.tsx
admin/src/static/index.html
backend/.env.example
backend/README.md
backend/grant/email/send.py
backend/grant/settings.py
backend/grant/templates/emails/comment_reply.html
backend/grant/templates/emails/contribution_update.html
backend/grant/templates/emails/proposal_approved.html
backend/grant/templates/emails/proposal_comment.html
backend/grant/templates/emails/proposal_contribution.html
backend/grant/templates/emails/recover.html
backend/grant/templates/emails/signup.html
backend/grant/templates/emails/team_invite.html
backend/grant/templates/emails/team_invite.txt
backend/grant/templates/emails/template.html
backend/grant/templates/emails/template.txt
backend/tests/test_data.py

Closes #104. Based off of #105 to prevent conflicts and incorporate its emails.
Changes the branding of emails, some strings on the backend, and admin with ZF Grants. Uses variables in most places for easy changes going forward.

Email & admin branding replacement

---

backend/grant/proposal/views.py
backend/grant/utils/auth.py
backend/tests/proposal/test_comment_api.py

Fixes a small issue where you could create drafts as a unverified user, but edits were rejected. Adds a new middleware for ensuring user is both auth'd and has verified email. Adds it to POST drafts and POST comment.

Enforce email verification server side

---

backend/grant/admin/example_emails.py
backend/grant/proposal/views.py
backend/grant/templates/emails/comment_reply.html
backend/grant/templates/emails/comment_reply.txt
backend/grant/templates/emails/contribution_update.html
backend/grant/templates/emails/contribution_update.txt
backend/grant/templates/emails/proposal_comment.html
backend/grant/templates/emails/proposal_comment.txt

Closes #109. Simply removes previews from comment and update emails. Due to the complexity and mismatch of python markdown libraries as compared with our frontend one, and the potential security implications since comments are posted before moderation, it's just easier to chop this Gordian knot and not include user content in emails.

No previews in emails

---

frontend/client/components/Profile/index.tsx
frontend/client/components/Profile/style.less
frontend/client/components/Proposal/index.less
frontend/client/components/Proposal/index.tsx

Closes #118. Adds minimum heights to the proposal and profile tabs (Just a magic number) to make the transition less jarring.

Minimum tab heights on proposals and profiles.

---

admin/src/components/UserDetail/index.tsx
admin/src/components/Users/UserItem.tsx
admin/src/store.ts
backend/grant/admin/views.py
frontend/client/components/AuthFlow/SignUp.less
frontend/client/components/AuthFlow/SignUp.tsx
frontend/client/index.tsx
frontend/client/modules/auth/index.ts
frontend/client/modules/auth/persistence.ts
frontend/client/store/configure.tsx
frontend/client/store/reducers.tsx
frontend/package.json

Closes #106.
To be compliant with GDPR and cookie laws, we have the following changes:
* Signup now requires explicit consent to the code of conduct, ToS, and privacy policy.
* Privacy policy will require a section on cookie usage to be fully compliant
* Code of conduct isn't a legal requirement, but seemed like a good idea to highlight during signup
* If the ZF team wants to use user emails for anything other than the grants site, we'll need to add another checkbox asking for explicit consent to do that.
* Adds the ability to delete users in the admin
* Unlike other forms of delete which would just flip a status to `DELETED`, this will actually purge the system of the account
* We may need to figure out some kind of db backup purging for #143, or exclude users from backups.
* Removes the …

GDPR and Cookie Compliance

---

backend/README.md

Pretty simple, just adds an example and documents `create-proposals`, a flask CLI command that lets you create X number of fake proposals (for testing).

Add create-proposals script to README

---

backend/grant/proposal/views.py
backend/tests/test_data.py

Uses `datetime`'s `fromtimestamp` instead of `dateutils`'s `parse` to parse milestone estimated dates.
As far as I can tell, the backend is expecting human readable dates passed in the API ala `"Fri, 30 Nov 2018 01:42:23 GMT"`, but the FE is sending unix timestamps (`1549505307`).
This PR adjusts the backend API to behave with the expectation of unix timestamps. 
`fromtimestamp` correctly handles parsing unix timestamps (int), wheras `parse` expects the human readable date that's not being sent:
``` 
Parser must be a string or character stream, not int
```

Fix Milestone Estimated Date Parser

---

frontend/client/components/Proposal/Updates/index.tsx
frontend/types/update.ts

Closes https://github.com/grant-project/zcash-grant-system/issues/139
Pretty simple, just removes the unused comments option on updates.
The API doesn't even provide `totalComments`, so I removed it from the type definition as well.

Remove comments option from updates

---

backend/grant/user/models.py
backend/grant/user/views.py
frontend/client/api/api.ts
frontend/client/components/Settings/Account.less
frontend/client/components/Settings/Account.tsx

Closes #146.
Adds an alert to the account settings tab when your email isn't verified to resend. I didn't touch the existing email blockers since they're subject to change. If we don't end up changing, we can just link to /settings?tab=account.

Resend email verification

---

frontend/client/components/MarkdownEditor/index.tsx
frontend/client/components/Proposal/Comments/index.tsx
frontend/client/components/Proposal/Comments/style.less

Closes https://github.com/grant-project/zcash-grant-system/issues/137
Replaces comment editor placeholder for unverified users with a disabled comment editor.

Show disabled comment form to unverified users

---

backend/grant/utils/enums.py
frontend/client/api/constants.ts
frontend/client/modules/create/utils.ts

Closes https://github.com/grant-project/zcash-grant-system/issues/133
This PR removes the 'dapp' category from the backend API and as an option on the frontend.

Finalize Categories

---

admin/src/types.ts
admin/src/util/ui.ts

*Actually* closes https://github.com/grant-project/zcash-grant-system/issues/133 by removing `dapp` category from admin in addition to app.

Remove 'DApp' category from Admin

---

backend/grant/app.py
backend/grant/utils/auth.py
frontend/client/api/axios.ts
frontend/client/modules/auth/actions.ts
frontend/client/modules/auth/reducers.ts
frontend/client/store/configure.tsx
frontend/server/components/HTML.tsx
frontend/server/render.tsx

Closes #132. 
- backend: sends a custom header on every api request with auth status
- frontend: axios watches this header and if it changes it calls the `checkUser` redux action
- this allows the redux store to update its auth status as soon as it learns about an authentication change via the header
- removes extra js scripts getting rendered to HTML, eliminating the double initialization behavior we were seeing
1. open two tabs 
1. sign-in in one tab
1. in other tab, click any link that causes an api request (profile, requests, explore)
1. you should see "Sign in" replaced by avatar icon as redux drinks deeply your user data
1. now sign-out in one tab
1. in the other tab take any action that interacts with api, notice the avatar change to "Sign in", redux should now be in the …

Handle External Auth Events & Fix Double Loading

---

backend/grant/proposal/models.py
frontend/client/components/Proposal/CampaignBlock/index.tsx
frontend/client/components/Proposal/CampaignBlock/style.less
frontend/client/utils/api.ts

Closes #205 
* Adds a banner to the campaign block that shows the bounty
* Adds the bounty to the `funded` hybrid property of proposals
* Allow proposals to instantly be marked as funded if they have sufficient bounty
* Fixes an issue where is_funded didn't take into account matching
* Make an RFP with a bounty
* Make a proposal with a target **below** that bounty
* Submit, approve, and publish it. Confirm it properly shows the banner, and switched to WIP stage.
* Make a proposal with a target **above** that bounty
* Submit, approve, and publish it. Confirm it properly shows the banner, and is still in funding stage.

Show bounty on proposal

---

frontend/client/components/Profile/index.tsx

Closes https://github.com/grant-project/zcash-grant-system/issues/218
- Updates all profile tab placeholders to have both title's and subtitles.
Profile tabs that are visible to just the user themselves remain directly addressing the user. Profile tabs that are public use passive language.

Standardize Profile Placeholders

---

frontend/client/components/RFP/index.less
frontend/client/components/RFP/index.tsx

Closes https://github.com/grant-project/zcash-grant-system/issues/225
Adds content only displayed on the listview to the detail view for RFPs.
So users don't have to go back and forth between views to have a total picture of the RFP.

Show tags and brief on RFP detail

---

backend/grant/proposal/models.py
frontend/client/components/ContributionModal/PaymentInfo.tsx
frontend/types/contribution.ts

Closes #246.
Removes sprout contributions in the least destructive, most minimal way possible. Simply omits the response of sprout address & memo from the backend, adds a warning to the frontend, and makes transparent the default. If we need to get more hands-on with this, let me know. Should make the transition to sapling much easier to implement than if we ripped the whole thing out.
* Contribute to a proposal, confirm you can't sprout it up

Remove Sprout contributions

---

admin/src/components/ProposalDetail/index.tsx
backend/grant/proposal/models.py
backend/grant/user/views.py
backend/migrations/versions/332a15eba9d8_.py
backend/migrations/versions/4af29f8b2143_.py
frontend/client/components/Profile/ProfileEdit.tsx
frontend/client/components/Profile/index.tsx
frontend/client/utils/social.tsx
frontend/types/social.ts

Closes #171. Closes #186. Closes #230. Closes #249.
- removes linkedin social media option (fe only, left capability on backend)
- include migration to remove existing linkedin social media entries
- fixes white space on social media "connect" buttons on user profile
- fix default Profile tab for non-authed user
- filter out non-LIVE proposal contributions for user profile "funded" tab
- remove 255 char limit for proposal reject reason (if you have not cleared your db you may encounter an error, I only updated the existing migration to create the field w/o a limit)
- should not be able to add linkedin social media to user profile
- social media connect button white-space should be ok (see #230)
- when navigating to the profile of user different from authenticated user, the first tab …

Various fixes

---

admin/src/components/ProposalDetail/index.tsx

No related issue. Solves bug described in https://github.com/grant-project/zcash-grant-system/pull/277#issuecomment-468991409
Adds better state handling to handle when the "Cancel & Refund" popconfirm is visible, so that it isn't shown simply when Handle & Confirm isn't disabled.

Handle only showing canel and refund popover correctly

---

frontend/client/components/Home/Intro.less

Closes #269. Overflow hidden on home intro. Just size your browser to 1000px on homepage, make sure it can't scroll horizontally.

Fix homepage horizontal scroll

---

backend/grant/admin/views.py
backend/grant/app.py
backend/grant/proposal/models.py
frontend/client/components/Home/Requests.tsx

Closes #287, addresses some issues found along the way.
* Sorts homepage by highest bounty first
* Fixes the edit RFP page endpoint to add `status` argument, handle missing `date_closes` argument
* Fixes linked RFPs with proposals that don't have bounties trying to cast `None` to `Decimal` (to add to contributions.)
* Confirm you can create and edit an RFP
* Confirm that homepage shows live RFPs sorted by bounty
* Confirm that a proposal can link to an RFP with no bounty

RFP Bounty Fixes

---

frontend/client/components/CreateFlow/Payment.tsx
frontend/client/components/CreateFlow/Review.tsx
frontend/client/components/CreateFlow/example.ts
frontend/client/modules/create/utils.ts
frontend/client/utils/constants.ts
frontend/client/utils/validators.ts

Closes #259.
* Requires sapling address for proposal payout address
* Add help copy and error messages to inform user
* Fixes review label for Payment step being "Governance" (holdover from ETH)
* Update example proposal to use sapling address
* Create a new proposal
* Set payment address to T address, confirm you get error
* Set payment to sprout address, confirm you get error
* Set payment to sapling address, confirm it works

Require sapling payout address

---

backend/grant/comment/models.py
backend/grant/milestone/models.py
backend/grant/proposal/models.py
backend/grant/rfp/models.py
backend/grant/user/models.py
backend/grant/user/views.py
backend/grant/utils/misc.py
backend/tests/user/test_user_api.py

Closes #245.
Generates a random id between `100000` and `2 ^ 31 - 1` for all public facing entities (Users, proposals, milestones, RFPs, comments, proposal updates, contributions, arbiters, avatars) It does so by generating a random number, checking if that id is already in use, and generating another. This should be really lightweight since this gives each entity `2,147,383,647` possible IDs, which I doubt we'll exceed any time soon.
Also removes GET /api/v1/users since the test started failing and this is a bad endpoint to have publicly available.
* Create a new user, confirm it gets a random id
* Create a proposal, confirm it and its milestones get random ids
* Comment on the proposal, confirm it gets a random id
* Post an update, confirm it gets a random id
* Set an arbiter, confirm …

Generate random ID for public facing entities

---

backend/grant/blockchain/bootstrap.py
backend/grant/blockchain/views.py
blockchain/src/node.ts

Closes #271 with some other small changes
* Sends only contribution IDs instead of the full serialized object for a smaller payload
* Fixes bootstrap endpoint response to be valid Flask response (was boolean)
* Blockchain watcher now starts from last confirmed tx block - min confirmations, to catch any potential straggler contributions
Start the blockchain watcher _after_ the flask server has started when you have pending contributions and a confirmed contribution with a valid txid, confirm it boots correctly.

Reduce payload size for bootstrap & other fixes

---

backend/grant/task/jobs.py

Small fix for a small issue found while testing #281, makes it so that a CANCELED proposal doesn't get moved to FAILED when the deadline is up if it was prematurely canceled for whatever reason.

Don't change proposal to FAILED if it was CANCELED

---

frontend/client/modules/proposals/reducers.ts

Closes #280. Makes funding required the default filter for stage filters.

Default browse proposals to FUNDING_REQUIRED

---

frontend/client/components/Profile/ProfileComment.less
frontend/client/components/Profile/ProfileComment.tsx

Closes #278.
- Uses `Markdown` renderer for user profile comments. 
- Converts profile comments dateCreated to milliseconds.

Profile Comments Bugs

---

backend/grant/proposal/models.py

Closes #301.
Returns contributions to auto-increment ids, for bip32 simplicity. Also of note, I had been passing in the wrong model the whole time, so that's embarrassing (expand the diff if you're confused.)

Revert contribution ids to be incremental.

---

frontend/client/components/Home/Intro.less
frontend/client/components/Home/Intro.tsx

Noticed this while testing on heroku, the way the image loads right now, it doesn't hold its shape until the png loads. This changes it to be a background image that maintains shape even before the image has loaded.

Homepage image loading improvement

---

admin/src/components/MFAuth/index.tsx
backend/.env.example
backend/grant/settings.py

Closes #306.
- adds `SESSION_COOKIE_DOMAIN` setting to backend (for production)
- fixes typo
- wait for the next heroku deploy (making sure to set SESSION_COOKIE_DOMAIN on backend)
- OR if you want to or already have dev domains set up
- edit [hosts](https://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want) or use [dnsmasq](https://medium.com/@kharysharpe/automatic-local-domains-setting-up-dnsmasq-for-macos-high-sierra-using-homebrew-caf767157e43)
- use `zfnd.test` as the root (or whatever)
- set backend `.env` `SESSION_COOKIE_DOMAIN="zfnd.test"` replacing 'zfnd.test' with whatever you are using
- set your browser to block third-party cookies 
- attempt to sign-in. It should successfully authenticate.

Session Cookie Domain Backend Setting

---

frontend/client/Routes.tsx
frontend/client/components/ErrorScreen/index.less
frontend/client/components/ErrorScreen/index.tsx
frontend/client/components/ErrorWrap.tsx
frontend/client/components/Footer/style.less
frontend/client/components/Header/style.less
frontend/client/index.tsx
frontend/client/pages/proposal.tsx

Closes #296 
Creates a common use `ErrorWrap` component that implements `componentDidCatch`, and renders an `ErrorScreen` component if it catches one. This is wrapped around the inside of `Routes` to catch individual pages throwing, and one at the very top to catch everything else. If the inner one catches, you maintain the page template and can navigate away normally. If the outer one catches (maybe because of an error in Template), it'll display _only_ the error screen as the full page.
Just a note, SSR does not respect componentDidCatch, so we're still stuck with ugly errors if SSR fails. Not sure if we should pretty this up, and if so, how we could leverage these react components for it.
Also if anyone objects to my copy, I'm open to any and all edits!
* Take any inner component and …

Frontend error handlers

---

backend/grant/app.py
backend/grant/proposal/models.py
frontend/client/components/ContributionModal/index.tsx
frontend/client/components/CreateFlow/Final.tsx
frontend/client/components/Profile/ProfilePending.tsx

Closes #297.
* Spiffs up some spots where the blockchain watcher goes belly up.
* Catches any uncaught `Exception` to send a proper json response instead of a blank 500
* Run the site with the blockchain watcher offline
* Try to make a contribution, confirm it shows an error
* Try to make a proposal, confirm it shows an error (during address validation)
* Run the blockchain watcher again, but this time add a `throw new Error` on `server/index.ts` for the `/contribution/addresses` endpoint
* Try to make a proposal, confirm it shows a different descriptive error
_*Opening a pending contribution looks like the previous screenshot. This is due to a difference in logic in how these two types of contributions are fetched / created._

Better contribution error displays

---

frontend/client/components/AuthRoute.tsx
frontend/client/components/Template/index.tsx
frontend/client/pages/auth.tsx
frontend/client/pages/create.tsx
frontend/client/styles/noscript.less
frontend/client/styles/style.less

Closes #308.
* Adds a persistent `<noscript>` banner to the top of every page (Except the homepage)
* Adds `<noscript>` warnings on pages that are particularly busted (create, auth)
* Run the site with production build, or flip the isDev booleans in loaders.tsx:64-65 to change style-loader for css extract plugin loader
* Disable javascript on the site (Click the button to the left of domain, site settings, block Javascript)
* Confirm that you see the warning on all non-homepage pages
* Confirm you see the extra warnings on pages that previously just showed white screens

Add noscript messages

---

backend/grant/app.py
backend/grant/extensions.py
backend/grant/proposal/views.py
backend/grant/user/views.py
backend/requirements/prod.txt
backend/tests/config.py
frontend/client/components/ContributionModal/index.tsx
frontend/client/components/CreateFlow/Team.tsx
frontend/client/components/DraftList/index.tsx

Closes #140.
* First pass at rate limiting. Nothing fancy here, it's limits from `flask-limiter` that are based on IP. I'm sure some of this could be improved upon.
* Improves error messaging in some places.
* Prevents inviting more than the maximum team size.
* Create and test the limits of:
* Drafts - 3/minute, 10/hour
* Proposal team invites - 10/minute, 30/day
* Contributions - 2/minute, 10/hour, 30/day
* Proposal updates - 1/minute, 5/day
* Comments - 2/minute, 30/hour, 100/day
* Try to invite more than 5 members to your team, confirm you can't
* Try to invite the same email twice, confirm you can't

Rate limits

---

admin/package.json
admin/src/components/Markdown/index.tsx
admin/src/components/Moderation/ModerationItem.tsx
admin/src/components/UserDetail/index.tsx
admin/src/util/md.ts
admin/yarn.lock
backend/grant/email/send.py

Closes #352. Closes #353.
- adds XSS sanitization to markdown rendered content on admin
- adds "reduced" style markdown for admin
- comment on a published proposal, enter the following naughty text:
```
XSS should not run when link is clicked
> hello <a name="n"
> href="javascript:alert('xss')">*you*</a>
Image should not render
```
- visit admin moderation, the comment should render without the image, clicking on the link should just reload the page
- visit user - comments and find the comment, it should render and behave as above
- create/edit a proposal, enter a naughty link in the markdown editor:
```
XSS should not run when link is clicked
> hello <a name="n"
> href="javascript:alert('xss')">*you*</a>
```
- visit admin proposals, find the proposal and click the link in the rendered …

XSS and Reduced Markdown for Admin

---

frontend/client/components/CreateFlow/Basics.tsx
frontend/client/components/Proposal/RFPBlock/index.tsx
frontend/client/components/RFPs/RFPItem.tsx
frontend/client/utils/api.ts
frontend/types/rfp.ts

Closes #168. Very straightforward, just make sure all the RFP links look correct and resolve to the correct RFP.

Slugify RFP urls

---

frontend/client/components/Proposal/index.tsx
frontend/client/components/RFP/index.tsx

Closes #351. Adds HeaderDetails to proposal pages and RFP pages.

HeaderDetails on proposals and RFPs

---

backend/grant/app.py
backend/grant/email/send.py
backend/grant/proposal/models.py
backend/grant/proposal/views.py
backend/grant/task/jobs.py
backend/grant/templates/emails/contribution_update.html
backend/grant/templates/emails/contribution_update.txt

Closes #347.
- emails related to contributions limited to one-per-contributor, and contributions with status CONFIRMED
- added `Proposal.contributors` hybrid field that produces users who have > 1 CONFIRMED contributions to proposal instance
- EmailSender constructor now takes in `app` since the logging now requires `current_app` which is missing when a new Thread is created
- 🆕 EmailSender is now set up automatically and stored on the request context object `g`, an ` @app.after_request` function is then used to start the EmailSender if it exists
- ~~passing the `current_app` into `EmailSender` is getting a little intense, it might be good to figure out how to create the `EmailSender` object implicitly (automagically) at the beginning of a request and then `start()` it after each request. …

Limit Contribution Related Emails

---

admin/src/components/ProposalDetail/index.tsx

Closes #339.
This sets the 'published' field in the Details section of proposal detail on admin to 'n/a' when it is 0. I opted to keep the field there since it is not derived.
- go to any unpublished proposal detail in admin and notice the "published" Details item is shown as "n/a"
- go to any live proposal, the published field should show formatted date

Render n/a when publishedDate is 0 (Admin)

---

frontend/.env.example
frontend/client/components/Header/index.tsx
frontend/client/components/Header/style.less
frontend/config/env.js

Adds a banner to the header (except on homepage) that indicates we're on testnet. Requires `TESTNET=true` in .env to show up.

Testnet banner

---

admin/src/components/ProposalDetail/index.less
backend/grant/proposal/views.py
backend/grant/user/views.py
frontend/client/components/CreateFlow/Basics.tsx

Closes #375. Closes #371. Closes #368. Closes #367.
- #375 adjust CSS for ProposalDetail Details values/labels such that the label is anchored to the bottom of the div instead of the top so it avoids overlapping with the value in the event that the value is long enough to wrap
- #371 adjust the urls sent out in the comment_reply & proposal_comment emails
- #368 allow_none=True for /user/<id> PUT end-point validation so we can successfully remove avatar
- #367 use `rfp.id` in link from proposal (creation step) to RFP
#375
- create a proposal and set an arbiter for it who's display name is long enough to wrap
- visit the proposal detail view in admin
- observe that the "arbiter" field of in Detail card wraps and that the label stays below the value
#371 
- comment on a proposal, check that …

Several bugs

---

backend/app.py
blockchain/src/index.ts
blockchain/src/webhooks/index.ts

Closes #370. Switches the bootstrapping from being this he-says-she-says between both backend and watcher, to some good ol' long polling from the watcher. Should have been this way from the start, much simpler!
To test, just try it out in a few ways:
* Start the watcher, wait a bit, then start the backend. Confirm the watcher bootstraps  again shortly.
* Start the backend, wait a bit, then start the watcher. Confirm the watcher bootstraps immediately.

Repeat bootstrap attempts

---

backend/.env.example
backend/grant/admin/views.py
backend/grant/proposal/views.py
backend/grant/settings.py
backend/grant/utils/misc.py
frontend/.env.example
frontend/client/utils/formatters.ts
frontend/config/env.js

- uses string replacement for block explorer url, replacing `<txid>` with, yes, the txid
- adds _adapter_ function to backend for doing so `make_explore_url`
- trigger contribution confirmation on a proposal (may use admin but if you use a bad txid the link will not work)
- check the emails and make sure the urls are correct
- check profile Funded tab "View transaction" links for confirmed contribs
- admin: pay a milestone payout (use a fake txid if you wish) make sure the email has correct URL format

String replacement for block explorer URL

---

frontend/client/components/Profile/ProfileInvite.less
frontend/client/styles/antd-overrides.less

Closes #398. Fixes a couple of cases where previously the brief of a proposal would push the actions off screen.
Now they properly ellipsize.

Prevent brief from overflowing

---

frontend/client/utils/api.ts

Closes #397. Properly rehydrates hex bignumber milestones. To test, refresh a proposal detail page (with js disabled if you're having a hard time catching it) and confirm you don't see NaN for the milestone amount.

Fix detail page milestone rehydration

---

backend/grant/proposal/views.py

Closes #396. Adds an additional check to not allow invitations to anyone on the team. To test, try to invite yourself.

Prevent self invite

---

backend/grant/app.py
backend/grant/commands.py
blockchain/.env.example
blockchain/package.json
blockchain/src/bin/genaddress.ts
blockchain/src/bitgo.ts
blockchain/src/env.ts
blockchain/src/index.ts
blockchain/src/node.ts
blockchain/src/server/index.ts
blockchain/src/server/middleware/errorHandler.ts
blockchain/src/store/actions.ts
blockchain/src/util.ts
blockchain/src/webhooks/index.ts
blockchain/src/webhooks/notifiers/contribution/index.ts
blockchain/tsconfig.json
blockchain/types/bitgo.d.ts
blockchain/yarn.lock

Closes #317.
* Adds an alternative to the `BIP32_XPUB` env var for address derivation using BitGo's API
* Requires 2 new env vars, `BITGO_WALLET_ID` & `BITGO_ACCESS_TOKEN`
* Enables configuration of a `FIXIE_URL` to proxy BitGo requests with a static IP using [Fixie](https://elements.heroku.com/addons/fixie)
* Adds a flask command `reset-db-chain-data` that deletes any data that relies on chain state, allowing you to keep data that doesn't without wiping out the whole DB
* Cleans up error logging a bit with a utility function to extract useful error text
* Apologies for the diff noise added by this, it was driving me bonkers to see `[object Object]` in our error logs so often though.
* Adds some better error handling to prevent silent failures in the blockchain watcher
* Make sure you …

Bitgo integration for mainnet

---

admin/.env.example
admin/.envexample
admin/package.json
admin/server.js
admin/yarn.lock
frontend/server/index.tsx

Closes #389.
Adds `express-sslify` to admin, just like the frontend. A little bit of misc cleanup along the way as well.
* Run admin in dev mode, confirm you can go on https
* Run `yarn build && yarn start`, confirm you get forced onto https

Enforce SSL on Admin

---

frontend/client/components/ErrorScreen/index.tsx

Closes #391 
The ErrorScreen component now shows a loader and refreshes on chunk errors, rather than displaying them to the user and reporting them to sentry. These usually either happen because of intermittent network failure, or a new version of the site was deployed with new chunk hashes. This shouldn't disrupt users since they would only encounter these errors while browsing to a new page anyway, so state isn't super important here.
* Run `yarn build && yarn start` and open a page.
* Open the network panel and go offline.
* Browse to a new page. Confirm you see a spinner for a half-second, and then the page refreshes.

Refresh page on chunk errors

---

blockchain/src/node.ts
blockchain/src/webhooks/index.ts
blockchain/src/webhooks/notifiers/contribution/index.ts

* Fixes uncaught errors from `node.getblockcount` in the scanBlock function causing silent failures
* Fixes an issue that may have caused blocks that failed to fetch from being skipped
* Fixes an issue where some vouts are not pubkeyhash transactions, and therefore do not have addresses
* Ups the retry interval after a failed block to 60 seconds from 5 seconds, to give the node more time to get ready
* Ups the number of retries to 10 from 5 before restarting the watcher
For the uncaught and block skip issues,
* Start up the watcher on a regtest node, then quickly kill the regtest node while it's scanning
* Confirm it warns about the failure, and tries again with a warning in 1 minute
* Start up the regtest node again, confirm it continues after 1 minute on the same block it failed on
For …

Blockchain watcher safety adjustments

---

frontend/client/components/Footer/index.tsx

Add zfnd.org link to footer

---

backend/grant/proposal/models.py
frontend/client/components/CreateFlow/Basics.tsx
frontend/client/modules/create/utils.ts
frontend/client/utils/validators.ts

Closes #390.
Defaults target to '0' instead of None due to db not-null constraint, and the use of `Decimal` everywhere throwing on empty string. Also adds some frontend validation to avoid users attempting to submit with '0' (It would error on the backend, but no warning on the frontend.)
Had to do a little hack to not show an error immediately on the basics screen since it defaults to an invalid value, but I think it's a pretty minor sin.

Default target to '0'

---

backend/requirements/prod.txt

Jinja 2.10 has a security issue, this just upgrades to the patched version.

upgrade jinja for security

---

backend/grant/proposal/models.py

Closes #425.
- truncates by rounding down the precision of proposal.funded (to match FE increment precision)
- create and stake a proposal
- create a contribution for the proposal
- from admin, alter the contribution amount to 0.0011111 & set a txid on it
- attempt to contribute the remaining amount to the proposal, confirm that you can do so and that the displayed funded value is truncated to 3 decimal places

Proposal funding precision

---

backend/grant/admin/views.py

Closes #426.
- makes sure the grant bounties & matching numbers are never negative, which was happening when a proposal had contributions exceeding matching and/or bounty amounts
- activate an RFP with matching and bounty
- create and stake a proposal for the RFP
- make a contribution to the proposal and overfund it via admin to an amount greater than matching & bounty
- proposal should be fully funded
- go to admin > financials and verify the grants bounty & matching numbers are not negative

Negative accounting bug

---

frontend/package.json
frontend/server/index.tsx
frontend/yarn.lock

Closes https://github.com/ZcashFoundation/zcash-grant-system/issues/435
Adds new `compression` middleware to GZIP static assets.
1. Run curl without accepting GZIP encoding: `curl http://localhost:3000/static/bundle.js --silent --write-out "%{size_download}\n" --output /dev/null`
2. Run curl with gzip encoding accepted: `curl http://localhost:3000/static/bundle.js --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null`
3. Confirm that gzip encoded download size is ~50% of original.
For some reason, I'm unable to get a `Content-Encoding` header back from express, but the content seems gzipped nonetheless.

Use gzip compression

---

backend/grant/admin/views.py

Currently, proposals that are cancelled will continue to admin action to assign arbiters.
This PR adds a filter to prevent Admins from being prompted to set arbiters on proposals that have been cancelled.

Filter Action Items

---

admin/src/components/Home/index.tsx
admin/src/components/ProposalDetail/index.tsx
admin/src/types.ts
admin/src/util/statuses.ts
admin/webpack.config.js
backend/grant/admin/views.py
backend/grant/utils/pagination.py

Originally I thought we could set status=DELETED when a Proposal is canceled. However, we still want users to be able to view their canceled proposals via direct link (as mentioned in #253).
That being the case, it made sense to implement the STAGE_NOT_CANCELED filter for the admin proposals list.
- backend: `paginate.py` support "not" filter for `STAGE_NOT_CANCELED`
- backend: add the filter to admin stats end-point for milestone payouts count
- admin: add the filter to the Home links for "without arbiter" & "with approved payouts"
- admin: add support to the Proposals list for the new filter
- admin: remove the "delete" button from ProposalDetail as it is not supported at present
- **extra** admin: separate the sourcemaps from the bundle to reduce the size on prod builds (webpack)
- …

Admin proposal stage not canceled filter

---

backend/grant/comment/models.py
backend/grant/proposal/views.py
backend/tests/test_data.py
frontend/client/components/MarkdownEditor/index.tsx

Increases maximum comment length's [per user feedback](https://github.com/ZcashFoundation/zcash-grant-system/pull/453#issuecomment-499596031).

Bump comment maximum to 5000

---

frontend/client/modules/proposals/reducers.ts

Sets the default stage filter to "ALL".
Showing users proposals that have received funding will help them to see that the platform is active, and hopefully excite them to participate more.

Default to "ALL" in stage filter

---

backend/grant/email/send.py

- set the contributor to `None` if the contribution is private for the `proposal_contribution` email
1. create a proposal & publish it
1. "contribute without attribution" from an authenticated account
1. send the contribution transaction naturally through zcash
1. the email subject and content should not display the contributor details

Fix contribution email

---

frontend/client/static/markdown/CONTACT.md

As discussed with @dternyak. Minor changes to the language on the ZF Grants contact page, intended to highlight the different communication channels for different sorts of inquiries.

update ZF Grants contact page
