ZcashFoundation/zcash-grant-system

- frontend/client/components/CreateFlow/Review.less
> Wrap review address

- README.md
Zcash is spelled Zcash, not ZCash 😁
> Update ReadMe with "Zcash" Typo

- .travis.yml
Closes #55. Runs tests and does a build. Shouldn't add much of a footprint.
> Blockchain microservice in CI

- frontend/client/components/Proposal/RFPBlock/index.tsx
Replaces the antd-pro Ellipsis usage which is causing SSR errors.
> replace antdp Ellipsis component

- frontend/client/components/Profile/ProfileEdit.tsx
- frontend/client/modules/create/utils.ts
Closes https://github.com/grant-project/zcash-grant-system/issues/195
- Removes email address validation from error check (in a somewhat hacky way)
- Doesn't check email address for missing field
- Removes email field
> Fix Edit Profile Save Button Always disabled

- admin/src/components/RFPForm/index.tsx
Removes unused `Moment` import that breaks `yarn build`.
Follow-up PR will be made to add `tsc check` to `pre-commit` to ensure fixes are made before commit.
> Fix Admin Build

- frontend/client/components/Proposal/index.tsx
Closes #217. Uses `ref` instead of randomly assigned ID which was didn't line up if it was server side rendered. Not sure what I was smoking here.
> Fix read more missing on SSR

- frontend/client/components/ContributionModal/PaymentInfo.tsx
> Remove dead link

- blockchain/src/server/index.ts
Closes #256. This might just be a band-aid though, we might want to get smarter about how much information these 2 pass back and forth to make sure it doesn't balloon like crazy.
> Up request limit to 50mb

- admin/package.json
- admin/yarn.lock
- frontend/package.json
- frontend/yarn.lock
Fixes some dependency issues. Reviewed their change logs, looks like most changes have been pretty innocuous.
> Upgrade ant-design-pro to 2.2.1

- backend/README.md
- backend/grant/app.py
- backend/grant/user/commands.py
Closes https://github.com/grant-project/zcash-grant-system/issues/272
To help seed admins in heroku, we can use the `set-admin` CLI command. It'll be run like so: 
```
heroku run flask set-admin <email|id> --app <app>
```
> Set Admin Command

- admin/package.json
- admin/src/components/ProposalDetail/index.tsx
- admin/src/components/Proposals/ProposalItem.tsx
- backend/grant/admin/views.py
- backend/grant/app.py
- backend/grant/blockchain/views.py
- backend/grant/comment/views.py
- backend/grant/email/views.py
- backend/grant/milestone/views.py
- backend/grant/parser.py
- backend/grant/proposal/views.py
- backend/grant/rfp/models.py
- backend/grant/rfp/views.py
- backend/grant/templates/emails/template.html
- backend/grant/templates/emails/template.txt
- backend/grant/user/views.py
- backend/requirements/prod.txt
- backend/tests/admin/test_admin_api.py
- backend/tests/proposal/test_api.py
- backend/tests/proposal/test_comment_api.py
- backend/tests/test_data.py
- backend/tests/user/test_user_api.py
- frontend/client/components/Home/Intro.less
- frontend/client/components/Home/Intro.tsx
Closes #262 
Closes https://github.com/grant-project/zcash-grant-system/issues/263
Closes https://github.com/grant-project/zcash-grant-system/issues/229
Closes https://github.com/grant-project/zcash-grant-system/issues/222
Closes https://github.com/grant-project/zcash-grant-system/issues/216
Hits a variety of low-hanging fruit. 
- #262: Make sure popover is no longer available when clicking cancel & refund when button is disabled
- #263 Make sure "delete" is no longer shown on the proposal listview
- #229 Attempt to post a comment longer than 1000 chars
- #222 Attempt to commit in `admin` with an unused import or otherwise fail `tsc`. Interestingly, we did already run `tsc` before `push`es, but since it was so troubling to have the heroku deployment fail, I figured we could also add it to …
> Various Fixes

- frontend/client/components/Header/Drawer.tsx
Closes #283 
* Closes drawer on link select
* Fixes menu item highlighting
* Adds a "Create account" link when logged out
* Navigate using the mobile drawer menu, confirm it closes on navigation
* Navigate to browse proposals, confirm only it is highlighted
* Navigate to create proposal, confirm only it is highlighted
> Mobile menu fixes

- frontend/client/utils/api.ts
Whoops, forgot to fix up these hexy boys.
> Rehydrate RFP bounty BNs

- frontend/package.json
- frontend/yarn.lock
Removes vulnerable packages, no other changes
> Upgrade react-mde to 7.0.4

- frontend/client/components/Profile/ProfileContribution.tsx
> Fix contact url

- backend/grant/email/send.py
_No issue associated_
Fixes `app` -> `current_app` typo.
> Fix Logging typo

- blockchain/src/webhooks/index.ts
Fixes:
> btw the new watcher code repeats forever when starting chain height is `0`, as is the case on my setup
> Watcher zero fix

- frontend/client/components/CreateFlow/index.tsx
- frontend/client/components/Proposal/Milestones/index.tsx
- frontend/client/modules/create/utils.ts
Closes #366 (I think.) I could replicate a preview error, but it didn't seem to be related to pending invites. Found some extras along the way. Here's what I fixed:
* Fixed a typescript escape of a potentially undefined `proposal.currentMilestone`
* Fixed back button on preview keeping it in preview
* Removed some unused code
> Create preview fix + extras

- backend/grant/admin/views.py
- frontend/client/components/Home/Requests.tsx
- frontend/client/components/RFPs/index.tsx
- frontend/client/static/locales/en/common.json
Replaces #412.
Uses the copy provided in #412, but fixes it so that the link renders. While making an RFP for this, I found a bug with date closed being required when it shouldn't be, so I fixed that too.
* Load homepage, confirm it looks ok with new copy
* Create an RFP without a close date, confirm it saves ok
> Update RFP copy + fix admin bug

- backend/.env.example
- backend/grant/app.py
- backend/grant/settings.py
Instead of piggy-backing on the cookie one
> Give CORS setting its own env var

- backend/grant/app.py
- backend/grant/proposal/models.py
- frontend/client/components/CreateFlow/Basics.tsx
- frontend/client/modules/create/utils.ts
- frontend/client/utils/validators.ts
- Adjust CORS policy to only allow set domains.
- Adjust validation for minimum proposal target amount to 0.01
- Fix rounding error that would hide KYC checkboxes in cases where bounties were lower than `0.5`.
> Release 1.1.1

- admin/src/components/Emails/emails.ts
- backend/.env.example
- backend/grant/admin/example_emails.py
- backend/grant/email/send.py
- backend/grant/email/subscription_settings.py
- backend/grant/milestone/models.py
- backend/grant/proposal/models.py
- backend/grant/settings.py
- backend/grant/templates/emails/admin_approval.html
- backend/grant/templates/emails/admin_approval.txt
- backend/grant/templates/emails/admin_arbiter.html
- backend/grant/templates/emails/admin_arbiter.txt
- backend/grant/templates/emails/admin_payout.html
- backend/grant/templates/emails/admin_payout.txt
- backend/grant/user/models.py
- backend/grant/utils/misc.py
- frontend/client/components/EmailSubscriptionsForm.tsx
- frontend/client/components/Settings/EmailSubscriptions.tsx
- frontend/client/utils/email.tsx
- frontend/types/email.ts
- frontend/types/user.ts
Closes #407.
- adds admin notification emails for:
- proposal needs review/approval/rejection
- proposal needs arbiter
- proposal awaits payout
- adds "Admin" section to notification settings for users that are admins
- adds example emails to admin site
- adds new backend environment variable `ADMIN_SITE_URL` for generating proposal urls to admin site
- existing admin users will have their Admin notifications OFF initially
- new users will have their admin notifications ON by default (just like the rest of the notifications)
- do not forget to set the new env var `ADMIN_SITE_URL` when deploying
- review the emails in "admin > emails" (last three), make sure the verbiage is A-OK
- setup 3 users, A B & C. Make A & B admins.
- user A: go to user > settings on main site, make sure all three …
> admin notifications

- admin/src/components/ProposalDetail/index.tsx
Displays information related to Milestones in human readable cards for Admins as part of proposal review.
> Admin Milestone Rendering

- blockchain/package.json
- blockchain/src/util.spec.ts
- blockchain/yarn.lock
- frontend/package.json
- frontend/yarn.lock
Certain dependency upgrades are incompatible with other sub dependencies. This PR partially reverts these incompatible versions.
> Partially revert dep updates

- frontend/client/Routes.tsx
- frontend/client/pages/proposal-tutorial.tsx
Hooks up Proposal Tutorial from https://github.com/ZcashFoundation/zcash-grant-system/pull/486 to a navigable route.
> Hookup Proposal Tutorial

- backend/requirements/prod.txt
- frontend/client/components/Header/Banner.less
- frontend/client/components/Header/Banner.tsx
- frontend/client/components/Header/Drawer.tsx
- frontend/client/components/Header/index.tsx
- frontend/client/components/Header/style.less
- frontend/client/components/RFP/index.tsx
- frontend/client/pages/email-verify.tsx
Create a banner that provides notice that new grants are not currently being accepted.
Remove proposal creation buttons on landing pages.
> Provide notice for the temporary pausing in acceptance of new grants
